apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations: {}
  name: azure-domifa-volume
  namespace: domifa
spec:
  encryptedData:
    azurestorageaccountname: >-
      AgB5E44IgvYuPi8EysA1S/zrME2Up7ZLfz40HM9egpFOsKtzcsHgPUv6UnDZtGCU8XpdGUfxMX4aEWWMmNTm80t35zO4SahzSXCRuiJeUBiUGY8cgsGPNrUF41f1IrYGO9ylNv3sNSAzW3mmLdplOrGXuIVafccI+VVYBH6mTmbWtoS9Ct5g/IHEDWjZpXXiaLdoPOBNl7D51a2FvXJ3aGHkraPUbtAXfis7omP8pWAtMNtVLikLhxRY1RgbX6xqyunCDZD6v3qeEUOzbrEOvO8tlpFONzPz0jzjAvPkPRqnrAB40RVsmyW+IIr0mLJySREfcslN8w3a/YQ1PQXIOoDYyIKczimruTYwuvvgZHR3sMl0dvv9VjfWSSoWAztCRcEPJdYMt/vVmLPHuG7L/O8DGRAwraXv9tAA0v43KbXvnWkC0b75JU1N3XHbkBGl2hWZLirKCBgwWOaQ+e58s6YHSLWPv+d2Wl+pckduz4XcqPk5AeK+mIji11cZYQ9d7xr7oi85O/hKInd7NcjRUH18byfoLb+eAfWhAIZVY2Qz0CytBreNVoYnVa18tqbMNRGfvV68GzQjB0znvveezD6CFw8CY9Tg6jYES42CWmeuN2nWHNLwpxcRN4lNi3SbD9F/+xofNAzrS9k/g1WvXF+WauTx52JVIcHbliIdZwn6SLJ9b35xrlEIhazDytduegqCZTJhru6PGNo=
    azurestorageaccountkey: >-
      AgB1xyUVmXM2OXFeYtK0FrjZD/mYuabZh/3Hxe14MNJ2BoxyvMZoBWvxI6P9P/rtOmseMC16REW95BA+Q1tFMdgk9Y0thp5mRSWYkyzwoyJdInEge8tOhBZeGm5S8Vf1B9s+icpVl85cNBIExb4aDU07qztFDSkPVY4Wc1mwI09QLD9gBc8JkLV9pSXuDz1Q51lGO8+Oybt90EwpHK3xlivb6Spm6wHZHAh8JeKC2TFgNS2hRcE7tZdRThVxOhs67H73edo1R4PlC+hasSzSfRyJbXNhXUcC0OIyoNPMlmpDAauBs4jZBQfwPoi3W1dA/SIhu2YHiTaOgpE/6PQa1MVshYo0j8698L4/QCU/EDYEvcqrGDJmX0VjJpNYsTWl3z16u7S2tNiQ4sJ//ahOzzW0Q6mQqfebuRYhzpFlRRlUzMmuNLrAOgwkwSMCKfVYe6LMAlEvf+bTLEVZ/NjmlwnoCktzeKq6J2mMRlm3Cst9LoKemy4gU1tA05sHqK3zpA/0kBuwQ9OlzNGplw6pwAEUyPgFf9XYItEJipc700/vjPCZJJ6V3tJawgbNETynemPYbeVWvaG/r33lnCj5b5mFOWXR9KS33feSV9dkCeLmgeAY8DqHg0VayNsuA3wDJF23SZ1VXGmQ01oCBtnpCl0n410YyDfGoRQfCidqYIz3CnKUkj3EbouCtyDaNTwpHJRJyVFojSR2ceItRMHbt4rPstPAESwwgKJKKg5/4Z3Dw+sS4YuGwS9aGQYq0p5h1+8FDfhx1cAPtG/Dj/uzKLOo0JMDDNlCkcwTCEbmHpfsdpx1Vcc8dJ9b
  template:
    metadata:
      annotations: {}
      name: azure-domifa-volume
    type: Opaque
