apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations: {}
  name: backend-sealed-secret
  namespace: domifa
spec:
  encryptedData:
    SECRET: >-
      AgCVFvBhNWgNGVwGhbTwQ6Sq4EK1QRZV5MZv9JU1/JC+flUC9x8GNjzjtzdwvpqqyOJw0M8Tz5kTG3jmjvBvr6umi6g4FRB6gaIkdN2r/ZUjEpB058YjkoCGdNMdFGf6NbNur35oKMnRaYMhR0XSKgO/phRfISrukzwlJxEBI5bARdLi5aczEILskETwJO9/GMxy1VGznGg2r+HhbBoAvC+waKfBfAp4Mh36Lrj25BvE22HfrgGxBRROaqaDGGUiX2uTNQaPnStnG3n91lkvRyGHXovFGAY8fXeie/jiKZCLraYiZa6W6Nurv01gn+1Su+hTuq62MME1pZbZvxKY9fAlL0dvyo+Kv28jEK/EOCMxBScPHGZbqB6EE9wJSf+4UCwuZKvsnPqxIiA7NBV5ypU8Fyz2sYQoEhmDA71ZzdAKDO5wbfENrrmCpScqQUTdPzBG+oKs7BxoykFYBIQTYpDGDvYf2I0XPgIlMm94dx6VsniurXWWxw8YZZ9tqhROL/x1lnkXrgQZ4OZSeSjfwWWQiddwxPJuCgRAPRTswEHT11he4UnCuUqUTLarS4/Ao8uvIvwapZT0uieNUaPzrYkJq/XCryES3ZXbPA5rZwUeREoTWt29IaZYN0u8vPoz5NokBaantsQ0lWXvkh0sZJQRxuRNmbJvkxyUJq5mxS/NQqt8f7dEm53+ptvWfilPKeiQmUj1WdLdCEZqa8+7HDdNbU7W5TSxS6nmv+sXvo3FOzpFELh7y1CLuoFgMTHEOJoXMUzb4656OfrgQaRE0U1ES5UZZVvdpJUTpnIZDbWbkb63K21dVxKJO7G144hFz9dOnB4qFj+7kB/EsM/2QyuUhaPPavnagYy9y+1AP4Mi7cC2SrvqVav/3GRoFVf/HmaZFfcqoHuFZY2ZFPrhVcALnqRtrVnraC2uPfQx62cmtLNcWOeP4anho8s=
  template:
    metadata:
      annotations: {}
      name: backend-sealed-secret
    type: Opaque
