apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: 'true'
  name: azure-domifa-volume
  namespace: domifa
spec:
  encryptedData:
    azurestorageaccountname: >-
      AgCGjtobFgMyxlzZXTZ3sbySTB9g9aTClqf0evWl1rxVmp0BnysDJgD/7Z5BH0ZIdBXZS1iiaKX79Ng03PosFTQIfTtTkD1ssf5uY9yisv3WltT3bWKs5uuzxWzfYtcxWEpgN+rdUbZM7ND05jAVFa19Ou5vV2thfPpsxCnfY+Gj458Shg44VYdx4K0B09WqKRJSyO+1wpipYfmLESIN+BBDtrKQL6X+/XZwc9IoSYsXxMhjXienKQHaP+WINx6muwkMgrVERuO4/v0V3b2Y+g18TZcAj356moeWjKY7dNL2ZJrSlBJH4fda+m76EnYhppH4lpfhBMlZUxyo/Dbj7VGnxkG0NnSfAQQSMnxL+GWnTOKv3p13TvdOCbhAcBXsff4j7Q80xviSWf4l7go1BauB1JvKgADGHU0DtsJMh+mzGIqkt9bgM8HMY2afgLLt9sDHLAyE00rUOOjy4RL+BHUzd1Z0mV+euqHMziJJ9GUC9pBzOXr4TXT54LUDaSdBIgYtpYnkC85SYrIZV3xkMm3FHT0ap4Ql2zoiaVlrBCKpd37q4bklCCMilgNdTrEW820Da0C8NwVFiMwSAlJtm80rUU9zAv/tWdW8IGhLf5cMxYwWffCUkAIDTSDl1ERAaPCGeTx3A3WDLLs8Q8Q0A4wlXdTK9YmiIKYEiqpDY+0vmrSVLecqrwMkFhuaSnYDJmgm1/bseEIsZps=
    azurestorageaccountkey: >-
      AgBjnfA+7m3UBls5bDE93b3n05vyhlwrHbyniK8r0FleKCiYX6ukKqGdYz2iyC92vZTHHQjQj7ojVMn5O+R8uwfhsDW3Z7StZTU6RZINMw5WBvLdq6XpaKKAYv4B0rP7KUOjb4R4ypDYputY4EBae7GzYO3YcyNTbBguWu6Jzwc29WiCB1P9VZ7sS5/egUN/OPAFMHUxvQe77BYdu4mIWyKiuU4/HeAyYs8CbIyF0MA8foalVYe2xvnyFMkNnZwX8Q2PM3JMyDTZj+5GA/TmjJ2vuAw3mk893pU/Gij+GsJg/IiVTdxOO53m3fo6T7YNzU1cKpHNxT1dvhoeV9SjxNdEeo4iMBORLNc2UcfS1nb+Bez1N0rUxkyqkoZUuk8cjy3b6jWvU5M9n5GZaI2dJUkzbk7Dj7g0sZHE2NOnbMOP/OeiUfWL0ZFQLQQTKs2dfc7B8LgTWFXz6Bh9F9SHjnnca0Bdhnycycm/shO1RjxHLdns2U49EoOAhuEoPL66jLvnrLsd4Fw5rkPnjDHmiLT0VKyh8eRHqn5y26ArRa6vYamGr/3zbZA79uP9GR9RTw0TEnM9r8IcqBoftpeHTfm5MjWRbrURC/smQshpSiokeWhtpogbb0ifYaA6BxDAjhibKfxOSpU9C0AePXghYSnbRn7SD9tcLyILICCMhqy6PcnGLcmwrBPCkDpWzdjwmMrwXFWQnK7fWHOjLdswRSTAdMz0mMw5zxbwpJwg3j68Vf8G0MqXT8aDzF3wES9khXjSP1wCQj7+/kS2ztk3u5SYS8X/KSHYEUZmv3wuiaMELOP/phcyEB2y
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: 'true'
      name: azure-domifa-volume
    type: Opaque
