apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: 'true'
  name: azure-domifa-volume
  namespace: domifa
spec:
  encryptedData:
    azurestorageaccountname: >-
      AgAtM6jowTuCuQYzJN1yYbzktkQ6OYUQYZgxyTsqhTHUh+33EGtjAySk6xsaqvwiirKnoi9gN2dwAuQlBv8iWgiwYMxrKQxBLXPWVUbaNi1L7GnVF3bMKzbMQmwURisX8JHWHtuM3x1r3VxJlamEIfPN2xKCt8GZYZlkt4UGIst8ZYz9p4HsDxGXu+1cO/LDvcmzAEn234vHhqD4H+wbirFXIFe4tqQlxftHH2XuvF2KfXkos3UoTUFacdBDqcGnDMz3/pgOpoPHTRaboRye9vS9P83jeglFD3slTj8WOVZEfc0VG7p6Ex0wmbuaHPczQGzS01d45UkitvaTbpud4sFTYWsnRKQ7JBzVvoz6mcdhOsO/XPPxxESXZj1RgcuCdpFKFNYypPYrB+RwAyt/NgFImqlrVosQsPX8ANlqtnvvk1bcFG03s+/pQSxtGNiMooPyiUbU8HHccYsOtbsWEJRdFFTBJQQjNgQmTDE/rHailtY+FIii+Dc2satows0GxkWaUQQISA/ynN6WnZckL8qosROHc7Jslr4de9AF4T40yEQYHsSF53LbdthWd+0O6F8fpnJi8H0TWeFHnhnAcmuITmuUSzWFj5a/4dlzBdKRYbY2c6fr+I7CS6r2E1KJcxxX0NkCT2Hw5Uhysac4YnTyAw9w1OXpXSPaae3204iUj+nBq6vzroH4B7swuH9+7UyHaQbuTqBYcLA=
    azurestorageaccountkey: >-
      AgDKiDPmimKpKWqPzJEvPS4jiw6DfDRPL0rsg1GE8REEE3vt9RSnytobgBdgJoswsddlXgMEzyPF50qF2nCJ+IwGemDOAdzjkgJNSE+L3J0ngyvO53xCU14+ImvJdikPlifTJFNcBavzfcT7ODc0PDJ3omgUq6OK2hw/MEuhPIDPRE9jyXPgc0op2/FKdw6swZOwQcal5CKHNhLQzj2ZZPp3qBF1WQEhY47VSGsLwEOpucAZ36MaFaZftxBNobwce6yRoUHT+b/UqU/nYJbZWPDc6Hai0KYmahz6IWY8qz1c+rNuEu3wL6L3BAECQYOdKWDP5xbRs5CcggdmHU9GiaZYTUB2GtfZSvXk1EFWktjb798rZjm824dr3l+b8mPZwkyrggbwKRQy7pMPQnrY3SCskBBF0m93H/04HFA5XtktvNuGcwM/JS0mLOxO47dAp/2BzE6uyMmGUw2OOweYdhGhS5ixML5htcxmqoduthufv2hgy3M3qK5tQ+2XuFA8tshXz3v6rxeQ/3qnJOSQR5N1fV3IdNw6L8lYx9AptCm59SkVn3qiuU4KJaDM2KxbUFYlAAtnb8PAYionI8KDRpT5QY+fzV2W/7Z+qqJP0uhZJiqrxJ8DlntmSOP0pMzg+LrZ6y76N5f736pxaM5xZnWNrKlr/JZwwZQ+tu+ZT8Ld4S7s5w36O8kTLVYRN25xyeCcHHXhmYAgvw7koz/a/1uoAS3VnaH9Z7TkixzQUL/W6e1S5/euN4koRICfq44QeTJVVt9uCCVSQOglfdNYHrDv1G2qiF7Fe/V3h2NJD5JJ+/cFhIvAOKh5
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: 'true'
      name: azure-domifa-volume
    type: Opaque
