apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: 'true'
  name: backend-sealed-secret
  namespace: domifa
spec:
  encryptedData:
    SECRET: >-
      AgBfopg5pbDfU/CksPAhcsPStn455QyNrmCzj43lmoTORUaab6vF/ud7xrpiVKlBn3f/rsIkP6PaAdwmt+H0ESBHP63mcZMrMExHBc27notWakV8O5rUjPzLaWyYjGBQLJIPXNq/GMqiKt/f9D9vj/g37OwpSAn9HkENqD+J4mLL9vibY8x1BGSg6sznDbmd8qQwEM3TzjAWuGkNjg0BezXXzrxFLaaP8piFjFBFY0cFpPoUP3v3oXtfXQw2jhoVbdGqubmjJdcM/MBAQtl1Ya4ggBWThsg+Y+fucr6Nhr/yDL7uSvDYIsaBctag9/EMbbJRKO1UgxJwfMW8C6OLqtOa4DvXqOPQ3i22myH5ie+PIevbHvn8JFThl+RaOTQwK9Fo2tLNIRtF+0FVKHf4ju9ldiLCzqu/3neZwnNLSGHgtwzMbSjWYOyKVjj9fqdZV6IOOftf/DU2us43okcU5reIw5oh6O7SYTs2UR0zCxZefybAecPuH5RfCnhskmXny65SIWc44xY5dH3eqGcWvg7j7HkI3ZPOTWZ3+mmiqdNnvBcC3eDPmdBj6rLB6jzs2CBd1kUBzdtxZD2vsTVaSjHJKjHfGQ4Z3RYfOzmIxtgd40maWfkapuiEmyOi0/3ogPR7oz7QfLqc0ekKZPYoO/iPb5Br+kbT1TutI3VzalWOQlT03OlJV04X7YHIQryJMSbV1wdgZynHmfhmf82BEm9DVaDKl1Fg0ksbHriNAhMkJSLlXINbo9+TsgysRbqBXitBacMZc4ICZ7wCvQCvwEraayJmQU0yHVY/5hGTaX6DoJ4Q75ZyxnGRv4foldujsqJxk7nPorEqbT3QJo2d0cANzSOV71bIJIyf1vivNHuCJZKdRwkbrtukdOZ5IIHIwp1SXL2MrSRTWEUPVaX7frGZ9ZK2CTtYW4OoaPilOssyUxc7BfsKIHPTAxY=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: 'true'
      name: backend-sealed-secret
    type: Opaque
